version: "3.7"

volumes:
  nginx-data:
  nginx-letsencrypt:
  nginx-db:

networks:
  proxy-network:
    name: proxy-network
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24

services:

  # Nginx Proxy Manager web app
  app:
    depends_on:
      - wireguard
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-manager
    network_mode: service:wireguard
    restart: unless-stopped
    environment:
      DB_MYSQL_HOST: "10.10.10.5" # IP address to db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "manager"  # Change to match db
      DB_MYSQL_PASSWORD: "password" # Change to match db
      DB_MYSQL_NAME: "nginx" # Change to match db
    volumes:
      - nginx-data:/data
      - nginx-letsencrypt:/etc/letsencrypt

  # MariaDB for Nginx Proxy Manager.
  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: nginx-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password' # Change to be secure
      MYSQL_DATABASE: 'nginx' # Change to be secure
      MYSQL_USER: 'manager' # Change to be secure
      MYSQL_PASSWORD: 'password' # Change to be secure
    volumes:
      - nginx-db:/var/lib/mysql
    networks:
      proxy-network:
        ipv4_address: 10.10.10.5
        
  # Wireguard client connection.
  wireguard:
    image: linuxserver/wireguard
    container_name: nginx-wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./wireguard:/config # Change this to the directory of you wg0.conf file.
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      proxy-network:
        ipv4_address: 10.10.10.3