version: "3.7"

services:
  # Wireguard client connection.
  wireguard:
    image: linuxserver/wireguard
    container_name: portainer-wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./wireguard:/config # Change this to the directory of you wg0.conf file.
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
        
  # Portainer agent.
  agent:
    image: portainer/agent
    container_name: portainer-agent
    network_mode: service:wireguard
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes