version: "3"

networks:
  tandoor-network:
    name: tandoor-network

volumes:
  mediafiles:
    name: tandoor-media
  staticfiles:
    name: tandoor-static
  database:
    name: tandoor-db

services:
  db:
    container_name: tandoor-db
    restart: unless-stopped
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: CHANGE_ME # must match app!
      POSTGRES_USER: djangodb
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - tandoor-network

  app:
    container_name: tandoor-app
    image: vabene1111/recipes
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - DEBUG=0 # Defaults to 1 (enabled) and will have more logs.
       # generate a secret key by running "base64 /dev/urandom | head -c50" command
      - SECRET_KEY=CHANGE_ME  # Provide secret key
      - GUNICORN_MEDIA=1
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=tandoor-db
      - POSTGRES_USER=djangodb
      - POSTGRES_PASSWORD=CHANGE_ME # must match db!
      - POSTGRES_PORT=5432
      - POSTGRES_DB=djangodb
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db
    networks:
      - tandoor-network