version: "3.9"

services:
  # Ghost CMS service
  ghost:
    image: ghost:4-alpine
    container_name: ghost
    restart: unless-stopped
    ports:
      - 2368:2368
    environment:
      # Change to match URL of your Ghost CMS portal. NOTE this is optional and can 
      # be removed. The Ghost portal will default to your URL declared with the path "/ghost"
      admin: https://ghost.example.com 
      url: https://blog.example.com # Change to match your website's URL
    volumes:
      - /path/to/content:/var/lib/ghost/content # Change me