version: "3.9"

networks:
  public-network:
    external: true
    name: public
    driver: bridge

volumes:
  certs-volume:
    name: traefik-certs

services:

  traefik:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs-volume:/letsencrypt
    networks:
      - public-network
    environment:
      - LINODE_TOKEN=CHANGE_ME # Get Linode API token
    command:
      # Enable dashboard (This will be available)
      - --api.dashboard=true
      # Allow insecure connection to dashboard
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=public
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=linode
      - --certificatesresolvers.letsencrypt.acme.email=CHANGE_ME # Domain's email
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=example.com # Change to your domain
      - --entrypoints.websecure.http.tls.domains[0].sans=*.example.com # Change to your domain
      - --log=true
      - --log.level=DEBUG
      - --log.filepath=/var/log/traefik.log

  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    volumes:
      - /path/to/authelia/config:/config # change to your volume 
    networks:
      - public-network
    expose:
      - 9091
    environment:
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      # Change to your login/auth domain (where you login)
      - traefik.http.routers.authelia.rule=Host(`auth.example.com`)
      - traefik.http.routers.authelia.entrypoints=https
      - traefik.http.routers.authelia.tls=true
      # update rd parameter to your login URL.
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.example.com/
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email
      - traefik.http.middlewares.authelia-basic.forwardauth.address=http://authelia:9091/api/verify?auth=basic
      - traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email

# ####################################################### #
#                                                         #
# Docker service template that uses Traefik and Authelia. #
#                                                         #
# ####################################################### #

  # service-template: # Change
  #   image: service-image # Change
  #   restart: unless-stopped
  #   networks:
  #     - public-network
  #   labels:
  #     - traefik.docker.network=public
  #     - traefik.enable=true
  #     # Change SERVICE_NAME to the name of your service
  #     - traefik.http.routers.SERVICE_NAME.entrypoints=websecure
  #     - traefik.http.routers.SERVICE_NAME.middlewares=authelia@docker
  #     - traefik.http.routers.SERVICE_NAME.rule=Host(`subdomain.CHANGEME.com`) # Change to your domain
  #     - traefik.http.routers.SERVICE_NAME.tls=true
  #     - traefik.http.routers.SERVICE_NAME.tls.certresolver=letsencrypt
  #     - traefik.http.services.SERVICE_NAME.loadbalancer.server.port=99999 # Change to service port