version: "3.9"

networks:
  portainer-network:
    name: portainer-network
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/24

volumes:
  portainer-data-volume:
    name: portainer-data

services:
  # Wireguard client connection.
  wireguard:
    image: linuxserver/wireguard
    container_name: portainer-wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./wireguard:/config # Change this to the directory of you wg0.conf file.
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

  #Portainer UI
  portainer:
    image: portainer/portainer-ce
    container_name: portainer-ui
    network_mode: service:wireguard
    restart: unless-stopped
    volumes:
      - portainer-data-volume:/data
    networks:
      - portainer-network

  # Portainer Agent Service
  agent:
    image: portainer/agent
    container_name: portainer-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      portainer-network:
        ipv4_address: 10.3.0.5 # Use this address to connection to agent from portainer UI.